# Robot Config
# Copyright (c) 2020 FRC Team 3260

joystick:
  ip: "127.0.0.1"                                        # IP address where joystick is running
  port: 2000                                             # Port where core should send its status

core:
  ip: "127.0.0.1"                                        # IP address where core is running
  joystickPort: 4000                                     # Port where joystick should send its commands
  vehiclePort: 6000                                      # Port where vehicle should send its state
